quickhitch/config/routes.rb
Quickhitch::Application.routes.draw do
  resources :conferences

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :conferences, only: [:create, :destroy]
  get "users/new"
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get "static_pages/home"

  

end

quickhitch/app/models/conference.rb
class Conference < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 200 }
	validates :code, presence: true
	default_scope -> { order('created_at DESC') }
end

quickhitch/app/models/user.rb
class User < ActiveRecord::Base
	has_many :conferences, dependent: :destroy
	before_save { self.email = email.downcase }
   before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

quickhitch/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

quickhitch/app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
   @conference = current_user.conferences.build(conference_params)
    if @conference.save
      flash[:success] = "Conference created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
   # respond_to do |format|
     # if @conference.update(conference_params)
    #    format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
    #    format.json { head :no_content }
   #   else
  #      format.html { render action: 'edit' }
 #       format.json { render json: @conference.errors, #status: :unprocessable_entity }
  #    end
#    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :code)
    end
end

quickhitch/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

   def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

quickhitch/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	@conference = current_user.conferences.build if signed_in?
  end
end

quickhitch/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
	@user = User.find(params[:id])
	@conferences = @user.conferences.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

quickhitch/app/helpers/application_helper.rb
module ApplicationHelper
end

quickhitch/app/helpers/conferences_helper.rb
module ConferencesHelper
end

quickhitch/app/helpers/sessions_helper.rb
module SessionsHelper
   def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

end

quickhitch/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

quickhitch/app/helpers/users_helper.rb
module UsersHelper
end

quickhitch/app/views/conferences/_conference.html.erb
<li>
  <span class="content"><%= conference.name %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(conference.created_at) %> ago.
  </span>
</li>

quickhitch/app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

quickhitch/app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

quickhitch/app/views/conferences/index.html.erb
<h1>Listing conferences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.name %></td>
        <td><%= conference.code %></td>
        <td><%= link_to 'Show', conference %></td>
        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference', new_conference_path %>

quickhitch/app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

quickhitch/app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conference.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @conference.code %>
</p>

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>

quickhitch/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

quickhitch/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

quickhitch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quickhitch</title>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <script src='http://code.jquery.com/jquery.min.js' type='text/javascript'></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link href='http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/base/jquery-ui.css' rel='stylesheet' type='text/css'>
    <%= link_to "QuickHitch", root_path, id: "logo" %>
    <div class="container">
      <div id="container">
        <div id='description'>
          <h1>Need a <strong>taxi</strong> to get to your conference?</h1>
          <h2>Share with someone who's going in the same direction!</h2>
        </div>
        <%= yield %>
      </div>
    </div>
</body>
</html>

quickhitch/app/views/shared/_conference_form.html.erb
<div id='conference-form'>
<%= form_for(@conference) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field" style="width: 50%; margin: 0 auto; resize: none; margin-top: 10px;">
    <%= f.text_area :name, placeholder: "Compose new conference..." %>
    <%= f.text_area :code, placeholder: "Conference code" %>
  </div>
  <%= f.submit "Post", class: "button" %>
<% end %>
</div>

quickhitch/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li style='list-style:none'>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

quickhitch/app/views/shared/_user_info.html.erb
<div id='user-info'>
<h1 style="margin-bottom:20px">
  <%= current_user.name %>
</h1>
<div style="margin-bottom:50px">
  <%= link_to "View My Profile", current_user, class: "link" %>
</div>
<div>
  <%= pluralize(current_user.conferences.count, "conference") %>
</div>
</div>

quickhitch/app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside>
      <div id='buttons'>
        <button id='conference'>Create conference</button>
        <button id='rider'>Find a ride!</button>
      </div>
        <%= render 'shared/user_info' %>
        <%= render 'shared/conference_form' %>
    </aside>
  </div>
<% else %>
  <div style="margin-top:100px">
    <%= link_to "Sign up now!", signup_path,
                                class: "button" %>
  </div>
<% end %>

quickhitch/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li style='list-style:none'><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

quickhitch/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

quickhitch/app/views/users/index.html.erb
<h2 style="margin: 50px 0 20px 0">Listing users</h2>

<table>  
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td style="font-size:10px"><%= user.password_digest %></td>
        <td style="padding-right:5px"><%= link_to 'Show', user, class: "link" %> </td>
        <td style="padding-right:5px"><%= link_to 'Edit', edit_user_path(user), class: "link" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "link" %>

<br>

quickhitch/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h2 style="margin:50px 0 0 -15px">Sign Up</h2>

<div class="row" style="margin-top:20px">
  <div>
    <%= form_for(@user) do |f| %>
		 <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

<br>
      <%= f.submit "Create my account", class: "button" %>
	<% end %>
  </div>
</div>

quickhitch/app/views/users/show.html.erb
<p id="notice"  style="margin-top: 50px"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

 <div class="span8">
    <% if @user.conferences.any? %>
      <h3>conferences (<%= @user.conferences.count %>)</h3>
      <ol class="conferences">
        <%= render @conferences %>
      </ol>
      <%= will_paginate @conferences %>
    <% end %>
  </div>

<%= link_to 'Edit', edit_user_path(@user), class: "link small" %> |
<%= link_to 'Back', users_path, class: "link small" %>